"""
Database models for agent sessions, query history, and user data.
These are Pydantic models that map to Supabase tables.
Uses CamelCaseBaseModel to ensure camelCase JSON output for frontend.
"""

from datetime import datetime
from typing import Optional, Dict, Any, List
from enum import Enum
from pydantic import Field
from api.schemas.base import CamelCaseBaseModel


class AgentStage(str, Enum):
    """Stages in the agent workflow."""

    IDLE = "idle"
    PLANNING = "planning"
    SEARCHING = "searching"
    ANALYZING = "analyzing"
    EXECUTING = "executing"
    FINALIZING = "finalizing"


class SessionStatus(str, Enum):
    """Status of an agent session."""

    ACTIVE = "active"
    COMPLETED = "completed"
    ERROR = "error"
    TIMEOUT = "timeout"


class QueryType(str, Enum):
    """Types of user queries."""

    STOCK_PRICE = "stock_price"
    COMPANY_INFO = "company_info"
    HISTORICAL_DATA = "historical_data"
    MARKET_ANALYSIS = "market_analysis"
    GENERAL_SEARCH = "general_search"
    MIXED = "mixed"


class AgentSession(CamelCaseBaseModel):
    """
    Represents an agent session stored in the database.
    Table: agent_sessions
    """

    id: Optional[str] = None  # UUID generated by Supabase
    session_id: str = Field(..., description="Unique session identifier")
    user_id: Optional[str] = Field(None, description="User ID if authenticated")
    stage: AgentStage = Field(default=AgentStage.IDLE)
    status: SessionStatus = Field(default=SessionStatus.ACTIVE)
    context: Dict[str, Any] = Field(default_factory=dict)
    memory: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(None, description="Session expiration time")

    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "sess_12345",
                "userId": "user_67890",
                "stage": "planning",
                "status": "active",
                "context": {"query": "giá cổ phiếu VNM"},
                "memory": {"stockSymbol": "VNM"},
                "metadata": {"userAgent": "Mozilla/5.0..."},
            }
        }


class AgentQueryHistory(CamelCaseBaseModel):
    """
    Stores history of agent queries and responses.
    Table: agent_query_history
    """

    id: Optional[str] = None
    session_id: str = Field(..., description="Reference to agent_sessions.session_id")
    user_id: Optional[str] = Field(None, description="User ID if authenticated")
    query: str = Field(..., description="User's original query")
    query_type: QueryType = Field(default=QueryType.MIXED)
    final_answer: Optional[str] = Field(None, description="Final synthesized answer")
    plan: Optional[Dict[str, Any]] = Field(None, description="Execution plan")
    tool_results: List[Dict[str, Any]] = Field(default_factory=list)
    critic_reviews: List[Dict[str, Any]] = Field(default_factory=list)
    iterations: int = Field(default=0, ge=0)
    execution_time: float = Field(default=0.0, ge=0)
    success: bool = Field(default=False)
    error_message: Optional[str] = Field(None, description="Error message if failed")
    tokens_used: Optional[int] = Field(None, description="Total tokens consumed")
    model_used: Optional[str] = Field(None, description="LLM model used")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = Field(None)

    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "sess_12345",
                "query": "giá cổ phiếu VNM",
                "queryType": "stock_price",
                "finalAnswer": "Giá cổ phiếu VNM hiện tại là 65,500 VND...",
                "iterations": 2,
                "executionTime": 3.45,
                "success": True,
            }
        }


class ToolExecution(CamelCaseBaseModel):
    """
    Records individual tool executions.
    Table: tool_executions
    """

    id: Optional[str] = None
    session_id: str
    query_history_id: Optional[str] = None
    tool_name: str
    tool_params: Dict[str, Any]
    tool_result: Optional[Dict[str, Any]] = None
    execution_time: float = Field(default=0.0)
    success: bool
    error_message: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "sess_12345",
                "toolName": "vnstock_get_quote",
                "toolParams": {"symbol": "VNM"},
                "toolResult": {"price": 65500, "change": 1.5},
                "executionTime": 0.5,
                "success": True,
            }
        }


class UserProfile(CamelCaseBaseModel):
    """
    Extended user profile information.
    Table: user_profiles (extends Supabase auth.users)
    """

    id: str  # Matches auth.users.id
    email: str
    display_name: Optional[str] = None
    preferences: Dict[str, Any] = Field(default_factory=dict)
    default_stocks: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    last_login_at: Optional[datetime] = None


class RateLimit(CamelCaseBaseModel):
    """
    Tracks API usage for rate limiting.
    Table: rate_limits
    """

    id: Optional[str] = None
    user_id: Optional[str] = None
    session_id: Optional[str] = None
    ip_address: Optional[str] = None
    endpoint: str
    requests_count: int = Field(default=1)
    window_start: datetime = Field(default_factory=datetime.utcnow)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# SQL Schema for creating tables in Supabase (for reference)
SQL_SCHEMA = """
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Agent Sessions Table
CREATE TABLE IF NOT EXISTS agent_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    stage TEXT NOT NULL DEFAULT 'idle',
    status TEXT NOT NULL DEFAULT 'active',
    context JSONB DEFAULT '{}',
    memory JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    INDEX idx_agent_sessions_user_id (user_id),
    INDEX idx_agent_sessions_session_id (session_id),
    INDEX idx_agent_sessions_status (status)
);

-- Agent Query History Table
CREATE TABLE IF NOT EXISTS agent_query_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id TEXT NOT NULL REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    query TEXT NOT NULL,
    query_type TEXT DEFAULT 'mixed',
    final_answer TEXT,
    plan JSONB,
    tool_results JSONB DEFAULT '[]',
    critic_reviews JSONB DEFAULT '[]',
    iterations INTEGER DEFAULT 0,
    execution_time FLOAT DEFAULT 0,
    success BOOLEAN DEFAULT FALSE,
    error_message TEXT,
    tokens_used INTEGER,
    model_used TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    INDEX idx_query_history_session_id (session_id),
    INDEX idx_query_history_user_id (user_id),
    INDEX idx_query_history_created_at (created_at)
);

-- Tool Executions Table
CREATE TABLE IF NOT EXISTS tool_executions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id TEXT NOT NULL REFERENCES agent_sessions(session_id) ON DELETE CASCADE,
    query_history_id UUID REFERENCES agent_query_history(id) ON DELETE CASCADE,
    tool_name TEXT NOT NULL,
    tool_params JSONB NOT NULL DEFAULT '{}',
    tool_result JSONB,
    execution_time FLOAT DEFAULT 0,
    success BOOLEAN DEFAULT FALSE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    INDEX idx_tool_executions_session_id (session_id),
    INDEX idx_tool_executions_query_history (query_history_id)
);

-- User Profiles Table
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    display_name TEXT,
    preferences JSONB DEFAULT '{}',
    default_stocks JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login_at TIMESTAMP WITH TIME ZONE
);

-- Rate Limits Table
CREATE TABLE IF NOT EXISTS rate_limits (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id TEXT,
    ip_address INET,
    endpoint TEXT NOT NULL,
    requests_count INTEGER DEFAULT 1,
    window_start TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    INDEX idx_rate_limits_user_id (user_id),
    INDEX idx_rate_limits_window (window_start)
);

-- Enable Row Level Security (RLS)
ALTER TABLE agent_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_query_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;

-- RLS Policies for agent_sessions
CREATE POLICY "Users can view own sessions" 
    ON agent_sessions FOR SELECT 
    USING (user_id = auth.uid() OR user_id IS NULL);

CREATE POLICY "Users can update own sessions" 
    ON agent_sessions FOR UPDATE 
    USING (user_id = auth.uid());

-- RLS Policies for agent_query_history
CREATE POLICY "Users can view own queries" 
    ON agent_query_history FOR SELECT 
    USING (user_id = auth.uid() OR user_id IS NULL);

-- RLS Policies for user_profiles
CREATE POLICY "Users can view own profile" 
    ON user_profiles FOR SELECT 
    USING (id = auth.uid());

CREATE POLICY "Users can update own profile" 
    ON user_profiles FOR UPDATE 
    USING (id = auth.uid());
"""
